"""Export wider portraits and review cutouts alongside front-facing avatars."""
from pathlib import Path
import hashlib,json
from PIL import Image
ROOT=Path(__file__).resolve().parent
expressions=['welcoming','explaining','thinking','delighted','concerned','surprised','playful']
files={};inputs={}
for expression in expressions:
    stem='portrait' if expression=='welcoming' else 'portrait-'+expression
    for suffix in ('','-transparent'):inputs[stem+suffix]=ROOT/f'{stem}{suffix}.png'
for stem in ('studio','studio-transparent'):inputs[stem]=ROOT/f'{stem}.png'
for old in ROOT.glob('previous-*.webp'):old.unlink()
for name,path in inputs.items():
    with Image.open(path) as original:
        for size in (640,1280):
            im=original.copy();im.thumbnail((size,size*2),Image.Resampling.LANCZOS)
            out=ROOT/f'{name}-{size}.webp';im.save(out,'WEBP',quality=88,method=6)
            files[out.name]={'bytes':out.stat().st_size,'size':list(im.size),'sha256':hashlib.sha256(out.read_bytes()).hexdigest()}
(ROOT/'web-images.json').write_text(json.dumps(files,indent=2)+'\n')
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Buddy · Presentation library</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f3ef;color:#24332c;font:16px/1.55 system-ui,sans-serif;--stage:#e4e8e2}main{max-width:1160px;margin:auto;padding:44px 28px 60px}header{max-width:780px}small{font:11px/1.5 ui-monospace,monospace;letter-spacing:.08em;color:#65766b}h1{font-size:clamp(28px,4vw,44px);letter-spacing:-.045em;line-height:1.1;margin:14px 0}p{color:#647167;margin:12px 0 24px}h2{font-size:22px;letter-spacing:-.025em;line-height:1.2;margin:0 0 14px}nav,.backgrounds{display:flex;flex-wrap:wrap;gap:8px;margin:24px 0}button{background:transparent;border:1px solid #b6c1b7;padding:10px 16px;border-radius:999px;color:inherit;font:inherit;cursor:pointer}button[aria-pressed=true]{background:#263f32;border-color:#263f32;color:white}button:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid #9b714a;outline-offset:4px}.preview{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr);gap:40px;align-items:center}.stage{background:var(--stage);border-radius:18px;text-align:center}.stage img{display:block;width:100%;height:auto;aspect-ratio:1;object-fit:contain}body[data-look=studio] .stage img{aspect-ratio:1/1.12}.message{display:flex;gap:14px;align-items:center;background:white;border-radius:16px;padding:20px;margin:20px 0}.message img{border-radius:50%;flex-shrink:0}.links{display:flex;flex-wrap:wrap;gap:14px;font-size:14px}a{color:#304d3b;text-underline-offset:4px}.note{font-size:13px}.expressions{margin-top:40px}.expression-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:24px;margin-top:24px}figure{margin:0;min-width:0}.expression-grid img{display:block;width:100%;height:auto;aspect-ratio:1;object-fit:contain;background:var(--stage);border-radius:16px}figcaption{padding:10px 0;font-size:14px}details{margin-top:40px;border-top:1px solid #d3dbd1;padding-top:24px}summary{cursor:pointer;font-size:20px;font-weight:600}.scenes{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:20px}.scenes img{width:100%;height:auto;border-radius:16px}footer{margin-top:32px;border-top:1px solid #d3dbd1;padding-top:18px}@media(max-width:650px){main{padding:24px 18px}.preview,.scenes{grid-template-columns:1fr}.preview{gap:24px}.expression-grid{grid-template-columns:1fr 1fr;gap:14px}button{font-size:14px;padding:9px 13px}}
</style></head><body data-look="portrait"><main><header><small>ORIGIN89 / BUDDY / APPROVED PRESENTATION</small><h1>One Buddy. Ready for your scene.</h1><p>Transparent portraits for website layouts and illustrations. A green circle for the small avatar. The same soft coat, focused eyes and gentle smile.</p></header>
<nav aria-label="Render composition"><button data-look="portrait" aria-pressed="true">Portrait</button><button data-look="studio" aria-pressed="false">Full character</button></nav>
<div class="preview"><section><div class="stage"><img id="cutout" src="portrait-transparent-640.webp" srcset="portrait-transparent-640.webp 640w, portrait-transparent-1280.webp 1280w" sizes="(max-width:650px) calc(100vw - 36px), 620px" width="1280" height="1280" alt="Buddy with a transparent background"></div><div class="backgrounds" aria-label="Preview background"><button data-background="#e4e8e2" aria-pressed="true">Light</button><button data-background="#20352e" aria-pressed="false">Dark</button><button data-background="#b9cdd9" aria-pressed="false">Blue</button></div><p class="note">The preview color belongs to the page. It is not included in the transparent image.</p></section><aside><h2>Green belongs to the avatar.</h2><p>Use the circular crop beside messages and in small interface spaces. The default keeps its tongue tucked in.</p><div class="message"><img src="../avatar/buddy-welcoming-96.webp" srcset="../avatar/buddy-welcoming-48.webp 48w, ../avatar/buddy-welcoming-96.webp 96w, ../avatar/buddy-welcoming-192.webp 192w" sizes="48px" width="48" height="48" alt="Buddy"><div><b>Buddy</b><div>Here to help.</div></div></div><div class="links"><a href="../avatar/index.html">See avatar sizes</a><a id="full" href="portrait-transparent.png">Transparent PNG</a><a id="scene" href="portrait-transparent.blend">Editable Blender scene</a><a href="render_cutout.py">Cutout render source</a></div><p class="note">For a new 3D scene, use the editable character and adapt its lighting to the environment.</p></aside></div>
<!-- EXPRESSIONS -->
<details><summary>Studio scenes, when the layout calls for one</summary><p>The green portrait and warm studio remain available as composed scenes.</p><div class="scenes"><figure><img src="portrait-640.webp" srcset="portrait-640.webp 640w, portrait-1280.webp 1280w" sizes="(max-width:650px) calc(100vw - 36px), 540px" loading="lazy" width="1280" height="1280" alt="Buddy in the green studio"><figcaption><a href="portrait.blend">Green portrait scene</a></figcaption></figure><figure><img src="studio-640.webp" srcset="studio-640.webp 640w, studio-1280.webp 1280w" sizes="(max-width:650px) calc(100vw - 36px), 540px" loading="lazy" width="1280" height="1434" alt="Buddy in the warm studio"><figcaption><a href="studio.blend">Full-body studio scene</a></figcaption></figure></div></details>
<footer><small>NATIVE TRANSPARENCY / SOFT DIRECTIONAL COAT / EDITABLE BLENDER SOURCE</small></footer></main><script>
document.querySelectorAll('button[data-look]').forEach(button=>button.addEventListener('click',()=>{const look=button.dataset.look;document.body.dataset.look=look;document.querySelectorAll('button[data-look]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const im=document.getElementById('cutout');im.srcset=`${look}-transparent-640.webp 640w, ${look}-transparent-1280.webp 1280w`;im.src=`${look}-transparent-640.webp`;document.getElementById('full').href=look+'-transparent.png';document.getElementById('scene').href=look+'-transparent.blend';}));
document.querySelectorAll('button[data-background]').forEach(button=>button.addEventListener('click',()=>{document.body.style.setProperty('--stage',button.dataset.background);document.querySelectorAll('button[data-background]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
</script></body></html>'''
gallery='<section class="expressions"><h2>One portrait, seven expressions.</h2><div class="expression-grid">'
for expression in expressions:
    stem=('portrait' if expression=='welcoming' else 'portrait-'+expression)+'-transparent'
    gallery+=f'<figure><img src="{stem}-640.webp" srcset="{stem}-640.webp 640w, {stem}-1280.webp 1280w" sizes="(max-width:650px) calc((100vw - 50px) / 2), 350px" width="640" height="640" loading="lazy" alt="Buddy, {expression}"><figcaption>{expression.capitalize()}</figcaption></figure>'
html=html.replace('<!-- EXPRESSIONS -->',gallery+'</div></section>')
(ROOT/'index.html').write_text(html)
print('Built Buddy presentation review:',len(files),'responsive images')
