//! Emits the package's two stylesheets from `src/palette.mjs`, which is the only
//! place the values live.
//!
//! Two files, split by what they DO rather than by which theme they carry:
//!
//!   tailwind.css   the @theme block. Only a Tailwind consumer has any use for
//!                  it, and it is what generates the utilities.
//!   themes.css     the whole palette as plain custom properties, both themes,
//!                  with the switching wired up. Works with or without Tailwind.
//!
//! There is deliberately no theme-light.css / theme-dark.css pair. Nobody
//! imports one theme on its own — the marketing site is dark forever, the docs
//! and the controller app both want switching — and the two are not peers
//! anyway: @theme must appear exactly once WITH LITERAL VALUES, and those
//! literals are the dark theme. A file named theme-dark.css would quietly be
//! doing two jobs, and a consumer importing theme-light.css alone would get
//! colours and no utilities, silently.
//!
//! Both files are committed, so this generator has the acceptance test the repo
//! relies on elsewhere: reshape the code, run it, `git diff`. An empty diff
//! proves the change was pure shape.
//!
//! No `color-mix()` anywhere. Tailwind 4's Lightning CSS pass silently mangles
//! it when an argument is a `var()` — it rewrote one to `var(--lens)` and
//! dropped the surrounding declarations outright.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { HERITAGE, QUALITY, TOKENS } from "./src/palette.mjs";

const here = dirname(fileURLToPath(import.meta.url));

const wrap = (text, width = 72, indent = "     ") =>
  text
    .split(" ")
    .reduce(
      (lines, word) => {
        const line = lines[lines.length - 1];
        if ((line + " " + word).trim().length > width) lines.push(word);
        else lines[lines.length - 1] = (line + " " + word).trim();
        return lines;
      },
      [""],
    )
    .join(`\n${indent}`);

const values = (theme, indent = "  ") =>
  TOKENS.map((t) => `${indent}--color-${t.name}: ${t[theme]};`).join("\n");

const heritage = (indent = "  ") =>
  HERITAGE.map((h) => `${indent}/* ${h.why} */\n${indent}--color-${h.name}: ${h.value};`).join(
    "\n\n",
  );

/** The base block carries each token's reasoning, since that is where a reader looks. */
const documented = () =>
  TOKENS.map((t) => `  /* ${wrap(t.why)} */\n  --color-${t.name}: ${t.dark};`).join("\n\n");

// Literal values, not var() indirection, and the reason is a fallback:
// `bg-nominal/10` compiles to a pair — a plain declaration for browsers without
// color-mix, then the color-mix itself. With a literal the fallback is computed
// correctly (#2f9d641a). With a var() the fallback degrades to full opacity, so
// a 10% glow becomes a solid block. Verified in this repo's build output.

const tailwind = `/* Generated by palette/build.mjs — do not edit.
   Values and reasoning live in palette/src/palette.mjs.

   Tailwind's vocabulary for the Origin 89 palette. Import this to get the
   colour utilities; the values are the dark theme, which is what an opacity
   modifier's literal fallback is computed from.

   This file alone leaves a site permanently dark, which is what the marketing
   site wants. Add themes.css to follow the OS preference or a toggle. */

@theme {
${values("dark")}

${heritage()}
}
`;

// The dark values appear here as a :root base as well as under an explicit
// [data-theme='dark']. The base is what lets a non-Tailwind consumer — the docs
// site — import this file ALONE and have the palette defined at all; the
// explicit block is what lets a toggle beat the media query in both directions.

const themes = `/* Generated by palette/build.mjs — do not edit.
   Values and reasoning live in palette/src/palette.mjs.

   The palette as plain custom properties, both themes, switching wired up.
   Needs no Tailwind — the docs site imports this on its own and maps
   --sl-color-* onto these.

   Alongside tailwind.css this also themes every Tailwind utility, because
   Tailwind compiles them to var(--color-x) rather than to a literal. One
   caveat worth knowing: an opacity-modified utility keeps a literal fallback
   computed from the dark theme, so on a browser without color-mix (roughly
   pre-2023) those specific utilities keep the dark hue in light mode. Right
   alpha, wrong hue, and only there. */

/* Dark is the base. This controller lives in a cabin at 4 a.m.; paper is the
   deliberate opt-in, never the default. */
:root {
${documented()}

${heritage()}

  /* The plate's rim carries the component boundary, because the fill is
     2.40:1 against its own ground and cannot. Deleting this is a safety
     regression, not a style change. */
  --color-action-rim: rgba(255, 255, 255, 0.85);
}

/* Every signal needs a darker twin on paper. Warning measures 2.12:1 on this
   ground and information 2.25:1 — a light colour on a light ground has nowhere
   to go. Hue was held in OKLCh; only lightness moved. */
@media (prefers-color-scheme: light) {
  :root {
${values("light", "    ")}
  }
}

/* An explicit choice beats the OS preference, in both directions. */
:root[data-theme='light'] {
${values("light")}
}

:root[data-theme='dark'] {
${values("dark")}
}

/* A reading's quality is never carried by colour alone: nominal and alarm sit
   about 13 apart under both protanopia and deuteranopia, which is close enough
   to be one colour at a glance. Each state pairs its hue with a channel that
   survives that.
${QUALITY.map((q) => `     ${q.state.padEnd(10)} --color-${q.token.padEnd(7)} ${q.channel} — ${q.note}`).join("\n")} */
.o89-counted { color: var(--color-fg); }
.o89-estimated { color: var(--color-info); }
.o89-stale { color: var(--color-muted); border-bottom: 1px dashed var(--color-line-strong); }
.o89-missing { color: var(--color-faint); letter-spacing: 0.08em; }

/* The ≈ is part of the state, not a flourish. It is what an operator who
   cannot separate the hues reads instead. */
.o89-estimated::before { content: '≈ '; }

/* Never a number. A missing probe is not 0.0 °C. */
.o89-missing::after { content: '——'; }
`;

writeFileSync(join(here, "tailwind.css"), tailwind);
writeFileSync(join(here, "themes.css"), themes);

console.log(
  `tailwind.css — @theme, ${TOKENS.length + HERITAGE.length} colours, dark literals\n` +
    `themes.css   — ${TOKENS.length} tokens x 2 themes + ${HERITAGE.length} heritage, switching wired`,
);
